# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2.1
jobs:
  build:
    macos:
      xcode: "11.2.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run:
          name: Check IdentitySdkCore
          command: |
            cd IdentitySdkCore
            pod install
            cd ../
            pod lib lint IdentitySdkCore.podspec --allow-warnings
      - run:
          name: Check IdentitySdkFacebook
          command: |
            cd IdentitySdkFacebook
            pod install
            cd ../
            pod lib lint IdentitySdkFacebook.podspec --allow-warnings
      - run:
          name: Check IdentitySdkGoogle
          command: |
            cd IdentitySdkGoogle
            pod install
            cd ../
            pod lib lint IdentitySdkGoogle.podspec --allow-warnings
      - run:
          name: Check IdentitySdkWebView
          command: |
            cd IdentitySdkWebView
            pod install
            cd ../
            pod lib lint IdentitySdkWebView.podspec --allow-warnings
  build-for-release:
    macos:
      xcode: "11.2.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run:
          name: Check IdentitySdkCore
          command: |
            cd IdentitySdkCore
            pod install
            cd ../
            pod spec lint IdentitySdkCore.podspec --allow-warnings
      - run:
          name: Check IdentitySdkFacebook
          command: |
            cd IdentitySdkFacebook
            pod install
            cd ../
            pod spec lint IdentitySdkFacebook.podspec --allow-warnings
      - run:
          name: Check IdentitySdkGoogle
          command: |
            cd IdentitySdkGoogle
            pod install
            cd ../
            pod spec lint IdentitySdkGoogle.podspec --allow-warnings
      - run:
          name: Check IdentitySdkWebView
          command: |
            cd IdentitySdkWebView
            pod install
            cd ../
            pod spec lint IdentitySdkWebView.podspec --allow-warnings

  publish:
    macos:
      xcode: "11.2.0"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run: pod trunk push IdentitySdkCore.podspec
      - run: pod trunk push IdentitySdkFacebook.podspec
      - run: pod trunk push IdentitySdkGoogle.podspec
      - run: pod trunk push IdentitySdkWebView.podspec
  build-sandbox:
    macos:
      xcode: "11.2.0"
    working_directory: ~/repo/Sandbox
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: Install CocoaPods
          command: gem install cocoapods --user-install
      - run: pod install
      - run: fastlane scan

default_workflows_filters: &default_workflows_filters
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

default_workflows_tags: &default_workflows_tags
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          <<: *default_workflows_tags
      - build-for-release:
          <<: *default_workflows_filters
      - publish:
          requires:
            - build-for-release
          <<: *default_workflows_filters
